# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb"}

modules = ["card.py"]

doc_url = "https://plops.github.io/cl_nbdev_test/"

git_url = "https://github.com/plops/cl_nbdev_test/tree/master/"

def custom_doc_links(name): return None
